# Use the official Nginx image as the base image
FROM nginx:latest

# Copy custom configuration file, if needed
# COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy static website files, if applicable
 COPY html /usr/share/nginx/html

# Expose the default Nginx port
EXPOSE 80